version: '3.8'

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestclean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
